.TH alignmargins 8
.SH "NAME"
alignmargins \- adjust the margins and the position of the printed contents on the paper
.SH SYNOPSIS
.B alignmargins [/path/to/align.ps]
.SH DESCRIPTION
This manual page documents briefly the
.B alignmargins
command.
.SH OPTIONS
alignmargins does not support any options.
.SH PURPOSE OF alignmargins
With this program you can adjust the margins and the position of the
printed contents on the paper. This way you get well-centered printouts and
you can make use of the whole imageable area of your printer, The driver
settings are overridden when this adjustment is used.

This is especially important when your printer is used with a driver for
another printer to which yours is compatible (for example many laser
printers are compatible to the HP LaserJet printers). Your printer prints
with this driver, but the non-printable margins are usually different or the
contents is even not centered. With this program you can fix these problems
.SH AUTHOR
alignmargins was written by Till Kamppeter.
.PP
This manual page was written by Michael Prokop
<mika@grml.org> for the grml project (but may be used by others).
