.TH dirvish-setup 8
.SH "NAME"
dirvish-setup \- create basic setup for dirvish(8)
.SH SYNOPSIS
.B dirvish-setup
.SH DESCRIPTION
dirvish-setup is a simple, console (dialog) based script for setting up
a basic configuration for the backup software named dirvish.
.SH OPTIONS
dirvish-setup does not support any options.
.SH USAGE EXAMPLE
.TP
.B dirvish-setup
Start console based dirvish-setup.
.SH BUGS
Probably. Please report bugs, feature requests and patches to the author.
.SH AUTHOR
dirvish-setup was written by Michael Prokop <mika@grml.org>.
.PP
This manual page was written by Michael Prokop
<mika@grml.org> for the grml project (but may be used by others).
