.TH grml\-bind 8 "2005-05-29" "grml-bind"
.SH "NAME"
grml\-bind \- a program to prepare a file on a read-only filesystem for writing
.SH SYNOPSIS
.B grml\-bind
.RI [ OPTIONS ] " <file/directory you want to edit>"
.SH DESCRIPTION
grml-bind is a program to prepare a file on a read-only filesystem for writing.
It copies the file to a ramdisk and mount --bind it back.
Very usefull for distributions like grml.
.SH OPTIONS
.TP
.B \-h
Show summary of options.
.TP
.B \-c
Create the file-mapping
.TP
.B \-r
Remove the file-mapping
.TP
.B \-v
Verbose (show what is going on)
.TP
.B \<>
If no Option is given, -c (create) is assumed
.SH EXAMPLES
.TP 
.B grml-bind -c /etc/inputrc
The file /etc/inputrc will be copied to /ramdisk/grml-bind/inputrc and mounted back with --bind
.TP
.B grml-bind -r /etc/inputrc
If you already unlocked /etc/inputrc (with grml-bind -c /etc/inputrc), then the mount will be removed and rm -r /ramdisk/grml-bind/inputrc will be executed
.TP
.B grml-bind -c /etc/vim
Now you can edit your vim configuration.
.TP
.B grml-bind -rc /etc/vim
To see what's going on
.SH BUGS/LIMITATIONS
.TP
.B no hardlinks
grml-bind can not work with hardlinks because grml-bind copies the files to another filesystem.
So hardlinks do not work.
.TP
.B only one mapping with the same name
grml-bind /a/b && grml-bind /c/b  (will not work)
.SH AUTHOR
This manual page was written by the grml-team. http://grml.org/ (c)Michael Gebetsroither <gebi@grml.org>
