.\" Filename:      grml-scripts.1
.\" Purpose:       man page for grml-scripts
.\" Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
.\" Bug-Reports:   see http://grml.org/bugs/
.\" License:       This file is licensed under the GPL v2.
.\"###############################################################################

.\"###############################################################
.TH grml\-scripts 1 "grml-scripts"
.SH "NAME"
grml\-scripts\-core \- core script collection for the grml distribution
.\"#######################################################
.SH "USER SCRIPTS"

.SS code2color
convert a source code to syntax highlighted HTML
.SS cpu-screen
output current / available cpu frequence (useful for integration into GNU screen)
.SS grml-screen
start screen session and fix console permissions
.SS ip-screen
print ip address of configured network interfaces to stdout.
.SS lesspipe.sh
wrapper for less

.SH "BUGS"
Probably. Please report any bugs you find and report
feedback and suggestions to the grml-team.
See http://grml.org/bugs/ for further information.
Thank you!

.SH "COPYRIGHT"
Copyright \(co 2004-2010 by the grml-team.
.\"###### END OF FILE ##########################################################
.\" vim:tw=60
