.TH grml-swapon 8
.SH "NAME"
grml\-swapon \- activate swap partitions with taking care of suspend signatures
.SH SYNOPSIS
.B grml\-swapon
.RI [ OPTIONS ]
.SH DESCRIPTION

grml-swapon is a small script for enabling swap partitions found in /etc/fstab.
Starting with grml 0.9 booting the live-cd system does not activate swap
parititions by default anymore. It is possible to force usage of swap partitions
via booting with the bootoption "swap". In case you forgot to use this
bootoption but want to use swap partition(s) anyway you could do that by running
"swapon -a". But the command "swapon" does not take of suspend signatures -
therefore the existance of grml-swapon.  grml-swapon acts based on the
information found in /etc/fstab. If your /etc/fstab is not up to date rebuild it
running "grml-rebuildfstab".

.SH OPTIONS
.TP
.B \-h, \-\-help
Show help text.
.TP
.B \-\-force
Force usage of swap partitions, activate them also if suspend signature is present.
.SH SEE ALSO
.BR grml-rebuildfstab (8).
.SH AUTHOR
grml-swapon was written by Michael Prokop <mika@grml.org>.
.PP
This manual page was written by Michael Prokop <mika@grml.org>
for the grml project (but may be used by others).
