.TH grml-init-multitail 8
.SH "NAME"
grml-init-multitail \- startup wrapper script around multitail
.SH SYNOPSIS
.B grml-init-multitail
.SH DESCRIPTION
This manual page documents briefly the
.B grml-init-multitail
command.
.SH OPTIONS
grml-init-multitail does not support any options.
.SH PURPOSE OF grml-init-multitail
multitail allows you to view multiple logfiles windowed on console.
grml-init-multitail is a small wrapper script to execute multitail
with the appropriate options for use at grml.
.SH AUTHOR
grml-init-multitail was written by the grml-team.
.PP
This manual page was written by Michael Prokop
<mika@grml.org> for the grml project (but may be used by others).
