.TH grml-setlang 8
.SH "NAME"
grml-setlang \- set language system-wide on grml system
.SH SYNOPSIS
.B grml-setlang
.RI " [ <language> ] "
.SH DESCRIPTION
This manual page documents briefly the
.B grml-setlang
command.
.SH OPTIONS
If you invoke grml-setlang without any further options you will get a
dialog based configuration frontend.  If you invoke grml-setlang with one
option, grml-setlang will take the first option as input for regenerating
/etc/default/locale according to the definitions in
/etc/grml/language-functions. If the provided option is not supported the
default (en_US) will be taken.
.SH USAGE EXAMPLES
.TP
.B grml-setlang de
Write german environment variables LANGUAGE, LANG, LC_MESSAGES, COUNTRY, CHARSET and TZ into /etc/default/locales.
.TP
.B grml-setlang at-utf8
Write austrian environment variables LANGUAGE, LANG, LC_MESSAGES, COUNTRY, CHARSET and TZ with unicode/utf8-support into /etc/default/locales.
.SH SEE ALSO
.BR grml-setkeyboard (8).
.SH AUTHOR
grml-setlang was written by Michael Prokop <mika@grml.org>.
.PP
This manual page was written by Michael Prokop
<mika@grml.org> for the grml project (but may be used by others).
