.TH grml-router 8
.SH "NAME"
grml-router \- set up your box as NAT-router
.SH SYNOPSIS
.B grml-router
.RI " start|stop|restart|info "
.SH DESCRIPTION
This manual page documents briefly the
.B grml-router
command.
.SH USAGE
grml-router reads the configuration file /etc/grml/routerconfig and uses the
variable OUTDEV for setting the WAN device. If OUTDEV is set to auto, the
device with a default route entry is used.

You have to set up a DNS-server server, or use the DNS-server provided by your
provider.

On the client(s) you have to specify the gateway manually, also specify a
nameserver. You can run the following commands on the client:

  route add default gw $IP_ADDRSS_OF_GW
  echo "nameserver $IP_OF_NAMESERVER" >> /etc/resolv.conf

.SH SEE ALSO
.BR grml-ap (8),
.BR grml-bridge (8).
.SH AUTHOR
grml-router was written by Ulrich Dangel <schula@grml.org> and Michael Prokop <mika@grml.org>.
.PP
This manual page was written by Michael Prokop
<mika@grml.org> for the Debian project (but may be used by others).
