.TH grml-quickconfig 8
.SH "NAME"
grml-quickconfig \- get fast access to some basic grml-scripts
.SH SYNOPSIS
.B grml-quickconfig
.SH DESCRIPTION
This manual page documents briefly the
.B grml-quickconfig
command.
.SH OPTIONS
grml-quickconfig does not support any options.
.SH NOTES
grml-quickconfig provides a console based interface to get fast
access to some basic grml-scripts like for example grml-network,
netcardconfig, grml-lang, grml-x and grml2hd.
.SH USAGE EXAMPLES
.TP
.B grml-quickconfig
Invoke the interface.
.SH AUTHOR
grml-quickconfig was written by Michael Schierl <schierlm-public@gmx.de>.
.PP
This manual page was written by Michael Prokop
<mika@grml.org> for the grml project (but may be used by others).
