.TH grml2ram 8
.SH "NAME"
grml2ram \- copy compressed GRML image to RAM
.SH SYNOPSIS
.B grml2ram
.SH DESCRIPTION
grml2ram is a script which copies the compressed GRML image to RAM and
unmounts /cdrom then. This allows ejecting of the CD (run 'eject /dev/cdrom' for example)
afterwards. Therefore running the grml live-cd without the need for a present grml-ISO is possible.
Please notice that you need enough free RAM to run grml2ram. At least enough space for the compressed
GRML image itself (about 52MB for grml-small and 685MB for grml) and for running userspace software
afterwards (at least 128MB are recommended) should be available.
.SH OPTIONS
grml2ram supports only the following option:
.TP
.B -f, \-\-force
Force copy process for GRML image even though the check for enough free RAM fails.
.SH SEE ALSO
.B bootoption toram
.SH AUTHOR
This manual page was written by Michael Prokop <mika@grml.org> for the grml project.
