.\" Filename:      grml-scripts-core.1
.\" Purpose:       man page for grml-scripts-core
.\" Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
.\" Bug-Reports:   see https://grml.org/bugs/
.\" License:       This file is licensed under the GPL v2.
.\"###############################################################################

.\"###############################################################
.TH grml\-scripts\-core 1 "grml-scripts-core"
.SH "NAME"
grml\-scripts\-core \- core script collection for the Grml distribution
.\"#######################################################
.SH "SCRIPTS"

.SS cpu-screen
output current / available cpu frequencies
(useful for integration into GNU screen)
.SS ip-screen
print ip address (IPv4 only) of configured network interfaces to stdout
(useful for integration into GNU screen)

.SH "BUGS"
Probably. Please report any bugs you find and report
feedback and suggestions to the Grml team.
See https://grml.org/bugs/ for further information.
Thank you!

.SH "SEE ALSO"
screen(1), grml-scripts(8)

.SH "COPYRIGHT"
This man page is copyright \(co 2004-2024 by the Grml team.
Included scripts are under various copyrights, please see
the sources.
.\"###### END OF FILE ##########################################################
.\" vim:tw=60
