.TH gsuggest.pl 1
gsuggest.pl \- google suggest, ask google for keyword suggestions
.SH SYNOPSIS
.B gsuggest.pl
.RI keyword " [ another-keyword ]"
.SH DESCRIPTION
This manual page documents briefly the
.B gsuggest.pl
command.
.PP
\fBgsuggest.pl\fP is a program that asks google for keyword suggestions
for the given keyword[s].
.SH USAGE EXAMPLE
.TP
.B gsuggest.pl grml
This will ask google for keyword suggestions based on the keyword 'grml'
and will return the results to standard out (stdout).
.SH OPTIONS
gsuggest.pl does not support any options.
.SH AUTHOR
gsuggest.pl was written by Michael Prokop <mika@grml.org>.
.PP
This manual page was written by Michael Prokop <mika@grml.org>
for the Debian project (but may be used by others).
