.TH gtf 1
.SH NAME
gtf \- generate mode timings using the GTF Timing Standard
.SH SYNOPSIS
.B gtf
.RI "x y refresh" " [ options ]"
.SH DESCRIPTION
This manual page documents briefly the
.B gtf
command.
.SH OPTIONS
The following options are available.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-verbose
Enable verbose printouts (traces each step of the computation).
.TP
.B \-f, \-\-fbmode
Output an fbset(8)-style mode description.
.TP
.B \-x, \-\-xf86mode
Output an XFree86-style mode description (this is the default if no mode description is requested).
.SH USAGE EXAMPLE
\fBgtf 1024 768 65\fP
.PP
Print modelines for resolution 1024x768 with refresh rate of 65.
.SH AUTHOR
gtf was written by Andy Ritger <aritger@nvidia.com>.
Taken from http://osdn.dl.sourceforge.net/sourceforge/gtf/gtf.c
.PP
This manual page was written by #USERNAME# <#EMAIL#>,
for the Debian project (but may be used by others).
