.TH iso-term 1
.SH "NAME"
iso-term \- wrapper script to run x-terminal-emulator in iso885915 mode
.SH SYNOPSIS
.B iso-term
.SH DESCRIPTION
This manual page documents briefly the
.B iso-term
command.
.SH OPTIONS
iso-term does not support any options.
.SH NOTES
iso-term is a simple wrapper script to run x-terminal-emulator in iso885915 mode.
This might be useful when you have to connect to a remote system which is running
in iso885915 mode even though your local system uses utf-8.
.SH USAGE EXAMPLES
.TP
.B iso-term
Run x-terminal-emulator in iso mode.
.SH AUTHOR
iso-term was written by Michael Prokop <mika@grml.org>.
.PP
This manual page was written by Michael Prokop
<mika@grml.org> for the grml project (but may be used by others).
