# Makefile for postfix

TARGETS = postmap alias reload

restart:
	/etc/init.d/postfix restart

reload:
	/etc/init.d/postfix reload

postmap:
#	postmap recipient_checks
#	postmap regexp_table
#	postmap sender_canonical
	postmap virtual

alias:
	newaliases

all: Makefile $(TARGETS)
