#!/bin/sh
# Filename:      postrm
# Purpose:       postrm script for package grml-etc-core
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
################################################################################

set -e

TO_UNDIVERT1="zlogin zprofile zshenv zshrc"
TO_UNDIVERT2=".zshrc"
TO_UNDIVERT3="vimrc"

undivert_gen() {
    if [ -f "$2/$1" -o "$2/$1".original ] ; then
        DEXT=${3:-original}
        dpkg-divert --remove --rename --package grml-etc-core \
            --divert $2/$1.$DEXT $2/$1 #> /dev/null
    fi
}

case "$1" in
    purge)
        for cmd in $TO_UNDIVERT1; do
            undivert_gen $cmd /etc/zsh
        done
        for cmd in $TO_UNDIVERT2; do
            undivert_gen $cmd /etc/skel
        done
        for cmd in $TO_UNDIVERT3; do
            undivert_gen $cmd /etc/vim
        done
    ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
    *)
        echo "postrm called with unknown argument $1" >&2
        exit 1
esac

#DEBHELPER#

exit 0

## END OF FILE #################################################################
