#!/bin/sh
# Filename:      postinst
# Purpose:       postinst script for package grml-scripts
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
# Latest change: Son Okt 28 17:18:56 CET 2007 [mika]
################################################################################

set -e

case "$1" in
   configure)

     [ -f /bin/egrep.dpkg-bak ] && mv /bin/egrep.dpkg-bak /bin/egrep
     [ -f /bin/egrep.old      ] && rm /bin/egrep.old
     [ -f /bin/fgrep.dpkg-bak ] && mv /bin/fgrep.dpkg-bak /bin/fgrep
     [ -f /bin/fgrep.old      ] && rm /bin/fgrep.old

     ;;

   *)
     exit 0
esac

#DEBHELPER#

## END OF FILE #################################################################
