#!/bin/sh
# Filename:      preinst
# Purpose:       preinst script for package grml-scripts
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
# Latest change: Son Okt 28 17:19:05 CET 2007 [mika]
################################################################################

set -e

case "$1" in
   upgrade)

     # remove (nowadays deprecated) "dpkg-divert"ion of [ef]grep
     dpkg-divert --list /bin/egrep | grep grml-scripts && \
     mv /bin/egrep /bin/egrep.old && \
     cp /bin/egrep.original /bin/egrep.dpkg-bak && \
     dpkg-divert --quiet --package grml-scripts --remove --rename --divert /bin/egrep.original /bin/egrep

     dpkg-divert --list /bin/fgrep | grep grml-scripts && \
     mv /bin/fgrep /bin/fgrep.old && \
     cp /bin/fgrep.original /bin/fgrep.dpkg-bak && \
     dpkg-divert --quiet --package grml-scripts --remove --rename --divert /bin/fgrep.original /bin/fgrep

     ;;
   *)
     exit 0
esac

#DEBHELPER#

## END OF FILE #################################################################
