#!/bin/sh
# Filename:      /etc/apt/listbugs
# Purpose:       display bugs of current running system (e.g. used inside grml-live)
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
# Latest change: Son Okt 14 00:21:54 CEST 2007 [mika]
################################################################################

[ -n "$SEVERITY" ] || SEVERITY="critical,grave,serious"

if ! [ -x /usr/sbin/apt-listbugs ] ; then
   echo "Error: /usr/sbin/apt-listbugs not available. Exiting."
   exit 1
fi

if ! [ -x /usr/bin/apt-show-source ] ; then
   echo "Error: /usr/bin/apt-show-source not available. Exiting."
   exit 1
fi

apt-listbugs -s $SEVERITY list \
    $(apt-show-source | grep -v -e 'not installed' -e '--------------' -e \
    'Version' | awk '{print $4;}' | grep -v '^[() ]*$'| sort | uniq)

# $ROOTCMD apt-listbugs -s $SEVERITY list \
#          $(dpkg --get-selections| grep '       install' | awk '{print $1})

## END OF FILE #################################################################
