# Filename:      zlogout
# Purpose:       system-wide .zlogout file for zsh(1)
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
# Latest change: Die Nov 16 13:25:11 CET 2004 [mika]
################################################################################
# nothing yet.
## END OF FILE #################################################################
