#!/bin/sh
# Filename:      firevim
# Purpose:       small wrapper to open any file from firefox with vim
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
# Latest change: Die Mai 03 17:05:35 CEST 2005 [mika]
################################################################################

xterm -e "vim $*"

## END OF FILE #################################################################
