#!/bin/sh
# Filename:      get_tw_cli
# Purpose:       get 3ware RAID controller command line interface tool (tw_cli)
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>, Wolfram Schlich <wschlich@gentoo.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
# Latest change: Thu Feb 09 12:20:30 CET 2006 [mika]
################################################################################
# Notice: this file is based on:
# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/www/www.gentoo.org/raw_cvs/gentoo-x86/sys-block/tw_cli/tw_cli-9.3.0.2.ebuild,v 1.1 2006/01/12 23:36:17 wschlich Exp $
################################################################################

if [ -r /etc/grml/lsb-functions ] ; then
  . /etc/grml/lsb-functions
else
  alias einfo="echo"
fi

PN="tw_cli"
PV="9.3.0.2"
MY_P="${PN}-linux-x86-${PV}"
SRC_URI_BASE="http://www.3ware.com/download/Escalade9000Series/${PV}"
SRC_URI="${SRC_URI_BASE}/${PN}-linux-x86-${PV}.tgz"
DOWNLOAD_URL="http://www.3ware.com/support/windows_agree.asp?path=/download/Escalade9000Series/${PV}/${MY_P}.tgz"

info() {
        einfo "get_tw_cli - get 3ware RAID controller command line interface tool (tw_cli)"
        einfo "==========================================================================="
        einfo ""
}

supportedcards() {
        einfo "This binary supports all current cards, including, but not limited to:"
        einfo ""
        einfo "PATA: 7210, 7410, 7450, 7810, 7850, 7000-2, 7500-4, 7500-8,"
        einfo "      7500-12, 7006-2, 7506-4, 7506-4LP, 7506-8, 7506-12"
        einfo ""
        einfo "SATA: 8500-4, 8500-8, 8500-12, 8006-2, 8506-4, 8506-12,"
        einfo "      8506-8MI, 8506-12MI, 9500S-4LP, 9500S-8, 9500S-12,"
        einfo "      9500S-8MI, 9500S-12MI"
        einfo "      9500S-8MI, 9500S-12MI"
        einfo ""
}

pkg_nofetch() {
        einfo "Please agree to the license at URL"
        einfo ""
        einfo "\t${DOWNLOAD_URL}"
        einfo ""
        einfo "And then use the following URL to download the correct tarball:"
        einfo ""
        einfo "\t${SRC_URI}"
        einfo ""
}

info
pkg_nofetch
supportedcards
# unp ${MY_P}.tgz

## END OF FILE #################################################################
