#!/bin/sh
# Filename:      grml-start
# Purpose:       start browser with information page on grml
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
# Latest change: Fre Jul 07 22:42:40 CEST 2006 [mika]
################################################################################

BROWSER=${BROWSER:-w3m}
#BROWSER=${BROWSER:-links2 -driver fb}
exec $BROWSER /usr/share/doc/grml-docs/startpage.html

## END OF FILE #################################################################
