#!/bin/dash
# Filename:      grml-init
# Purpose:       fix tty permissions and run zsh
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
# Latest change: Sam Jun 25 12:11:15 CEST 2005 [mika]
################################################################################

# export variable USER for use withing GNU screen:
  export USER=`id -un`

# fix rungetty:
  TTY=`tty`
  sudo chown $USER.$USER $TTY

# now start the shell:
  exec /bin/zsh

## END OF FILE #################################################################
