#!/bin/dash
# Filename:      grml-init-multitail
# Purpose:       fix tty permissions and run multitail
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>,
#                   (c) Michael Gebetsroither <gebi@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
################################################################################

# export variable USER for use withing GNU screen:
  export USER=`id -un`

# fix rungetty:
  TTY=`tty`
  sudo chown $USER.$USER $TTY

# now start the shell:
  exec /usr/bin/multitail -o 'check_mail:0' /var/log/syslog

## END OF FILE #################################################################
