#!/bin/sh
# Filename:      grml-config-user
# Purpose:       interface for configuring userland software on grml system
# Authors:       grml-team (grml.org), (c) Nico Golde <nico@grml.org>, (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
# Latest change: Mon Dec 05 11:12:49 CET 2005 [mika]
################################################################################

PATH=${PATH:-'/bin/:/sbin/:/usr/bin:/usr/sbin'}

# set up some variables
DIALOG=$(which dialog)
PN=$(basename $0)

allover() {
MENU=$($DIALOG --stdout --clear --title "$PN" --menu \
"Configure userland tools." 0 0 0 \
"grml-mutt" "Configure the mutt MUA" \
"grml-muttng" "Configuration of mutt next generation" \
"grml-slrn" "Configure the slrn newsreader" \
"exit" "Exit this program")

retval=$?

case $retval in
  0)
        if [ $MENU == grml-mutt ]; then
          exec grml-mutt
        fi
        if [ $MENU == grml-muttng ]; then
          exec grml-muttng
        fi
        if [ $MENU == grml-slrn ]; then
          exec grml-slrn
        fi
        if [ $MENU == exit ]; then
          exit
        fi
        ;;
  1)
        echo "Cancel pressed.";;
  255)
        echo "ESC pressed.";;
esac
}

allover

## END OF FILE #################################################################
