#!/bin/sh
# Filename:      loadavg-screen
# Purpose:       output load average (replacement for GNU screen 4.x %l escape)
# Authors:       grml-team (grml.org), (c) Chris Hofstaedtler <ch@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
#******************************************************************************

cut -d' ' -f1-3 /proc/loadavg
