#!/bin/sh
# Filename:      wm-ng
# Purpose:       a wrapper script to call fluxbox with some additional features activated
# Authors:       grml-team (grml.org)
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
################################################################################

gkrellm -g -1+26 &

(sleep 2; idesk &) &

fluxbox

exit $?

## END OF FILE #################################################################
