#!/bin/sh
# Filename:      zsh-login
# Purpose:       run zsh with login option
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
# Latest change: Don Mär 29 16:02:01 CEST 2007 [mika]
################################################################################

[ -r /etc/grml_version ] && GRMLVERSION=$(cat /etc/grml_version) || GRMLVERSION='(no version information available)'

echo "

Welcome to grml ${GRMLVERSION}!

New to grml? Want to read some documentation?
Start via running 'grml-info'.
Get tips and hints via 'grml-tips \$KEYWORD'.
New to zsh? Run 'zsh-help'.

Switch to other consoles via alt-F<number> keys.

Happy hacking!               http://grml.org/
"

[ -r /etc/release_info ] && cat /etc/release_info

CMDLINE=$(cat /proc/cmdline)
case "$CMDLINE" in
   *swspeak*|*blind*|*brltty*|*speakup*)
      if [ -x /usr/bin/flite ] ; then
         aumix -w 90 -v 90 -p 90 -m 90
         flite -o play -t "Finished booting"
      fi
      ;;
   noquick*|startx*)
      # do nothing
      ;;
   *) # by default run grml-quickconfig, but only if running as root
      if [ $(id -u) = "0" ] ; then
	 # do not run grml-quickconfig on grml-small
	 if ! grep -q small /etc/grml_version ; then
            [ -x /usr/sbin/grml-quickconfig ] && /usr/sbin/grml-quickconfig
         fi
      fi
esac

exec /bin/zsh -l

## END OF FILE #################################################################
