#!/bin/sh
# Filename:      grml-postfix
# Purpose:       wrapper script to configure postfix
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
################################################################################

PATH="/bin:/usr/bin:/sbin:/usr/sbin"
LANG=C
LC_ALL=C

if [ "$(id -ru)" != "0" ] ; then
   echo Error: become root before starting $0 >& 2
   exit 100
fi

dpkg-reconfigure postfix

## END OF FILE #################################################################
