#!/bin/sh
# Filename:      grml-nessus
# Purpose:       prepare nessus for use on grml system
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
# Latest change: Mon Sep 11 17:31:07 CEST 2006 [mika]
################################################################################

PATH=${PATH:-'/bin/:/sbin/:/usr/local/bin:/usr/bin:/usr/sbin'}
PN=`basename "$0"`

[ "`id -u`" != "0" ] && exec sudo "$0" "$@"
. /etc/grml/lsb-functions

# welcome screen
dialog --stdout --title "$PN" --msgbox "Welcome to $PN!

This script will prepare your grml system
for use with nessus[d].

Report bugs, send wishes and feedback to the grml team:
http://www.grml.org/ - contact (at) grml.org
" 12 65

# add user
dialog --stdout --title "$PN" --yesno "Run nessus-adduser for adding user?" 0 0
retval=$?
case $retval in
  0)
     einfo "Adding user for nessusd."
     nessus-adduser ; eend $?
     ;;
  1)
     ewarn "Cancel pressed."
     ;;
  255)
     ewarn "ESC pressed."
     ;;
esac

# create certificate
dialog --stdout --title "$PN" --yesno "Run nessus-mkcert?" 0 0
retval=$?
case $retval in
  0)
     einfo "Running nessus-mkcert."
     nessus-mkcert ; eend $?
     ;;
esac

# run nessusd
dialog --stdout --title "$PN" --yesno "Start nessus daemon now?" 0 0
retval=$?
case $retval in
  0)
     einfo "Starting nessus daemon. This might take some time [for initializing plugins]."
     if [ -r /etc/nessus/nessus-services ] ; then
        [ -L /var/lib/nessus/nessus-services ] || ln -s /etc/nessus/nessus-services /var/lib/nessus/nessus-services
     else
        [ -d /var/lib/nessus/nessus-services ] || mkdir /var/lib/nessus/nessus-services
     fi
     nessusd -D ; eend $?
     ;;
  1)
     ewarn "Cancel pressed."
     ;;
  255)
     ewarn "ESC pressed."
     ;;
esac

infoscreen() {
dialog --stdout --title "$PN" --msgbox "Thanks for using $PN!

For more information on nessus take a look at the manpage
(man 1 nessus) and the nessus webpage at www.nessus.org

#######################################################

Report bugs, send wishes and feedback to the grml team:
http://www.grml.org/ - contact (at) grml.org
" 13 65
}

# run nessusd
dialog --stdout --title "$PN" --yesno "Run nessus client (requires X window system) now?" 0 0
retval=$?
case $retval in
  0)
   infoscreen
   nessus
     ;;
  1)
     ewarn "Cancel pressed."
     ;;
  255)
     ewarn "ESC pressed."
     ;;
esac

## END OF FILE #################################################################
