#!/bin/sh
# Filename:      noeject
# Purpose:       wrapper script to avoid ejecting of CD-ROM when rebooting/halt grml system
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
# Latest change: Thu Nov 10 23:18:35 CET 2005 [mika]
################################################################################

touch /etc/noeject
exec $*

## END OF FILE #################################################################
