#!/bin/sh
# Filename:      noprompt
# Purpose:       wrapper script to avoid prompting when rebooting/halt grml system
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
# Latest change: Thu Nov 10 23:17:55 CET 2005 [mika]
################################################################################

touch /etc/noprompt
exec $*

## END OF FILE #################################################################
