#!/bin/sh
# Filename:      service
# Purpose:       small wrapper script for /etc/init.d/-script
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
# Latest change: Son Aug 07 12:17:00 CEST 2005 [mika]
################################################################################

/etc/init.d/$*

## END OF FILE #################################################################
